"""Add text_tags and text_tag_association tables

Revision ID: b0128aaa942b
Revises: 7c6dc61d91bd
Create Date: 2026-02-16 16:11:24.300847

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "b0128aaa942b"
down_revision = "7c6dc61d91bd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "text_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "text_tag_association",
        sa.Column("text_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["text_tags.id"],
        ),
        sa.ForeignKeyConstraint(
            ["text_id"],
            ["texts.id"],
        ),
        sa.PrimaryKeyConstraint("text_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("text_tag_association")
    op.drop_table("text_tags")
    # ### end Alembic commands ###
