# Install python and node. Run lint and unit tests.

name: 'Basic (Unit) Tests'
# **Why we have it**: Automatically run tests to ensure code doesn't introduce regressions.
# **Who does it impact**: Python small-scale "unit" tests.

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Poetry
        run: |
          python -m pip install poetry==1.4.1

      - name: Install Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
          cache: 'poetry'

    
      - name: Install dependencies and cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: make install-python

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
      
      - name: Lint
        run: |
          source env/bin/activate
          make lint-check
  
      - name: Build docs
        run: |
          source env/bin/activate
          make docs
          
  run-py-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
          cache: 'pip'

      - name: Install Poetry
        run: |
          python -m pip install poetry==1.4.1
    
      - name: Install dependencies and cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: make install-python

      - name: Run Tests
        run: make coverage
      
      - name: Check coverage
        run: make coverage-report

  run-js-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci
      
      - name: Run tests and check coverage
        run: make js-coverage
